### ISSUE TITLE
Demo page leads to 404

### ISSUE THREAD

**Issue by markschellhas** [efeskucuk/svelte-color-picker#12]
![Screenshot 2020-11-04 at 16 26 59](https://user-images.githubusercontent.com/3170906/98130539-a707f900-1eba-11eb-9448-59bc3dfa1861.png)

**Comment by markschellhas** [comment]
Submitted correction in pull request #13

**Comment by efeskucuk** [comment]
Issue is resolved with #13 . Thanks!
